### Filtrado de Datos:

---
### Uso de .loc[ ] y .iloc[ ]
---
En Pandas, el filtrado o selección de datos es esencial para explorar y manipular DataFrames.

Los métodos principales para seleccionar datos concretos de un DataFrame y poder manipularlos son loc e iloc .

.loc[ ] y .iloc[ ]
Ambos métodos se usan para acceder a subconjuntos de datos, pero con diferentes lógicas:

### <span style="color:darksalmon;">.loc[ ]: Selección basada en etiquetas (nombres) de filas y columnas.</span>

```python
#Sintaxis general
df.loc[etiqueta_filas,etiqueta_columnas]

Uso típico de .loc[]:

df.loc[fila, columna]
```
Si no se especifica columna, se seleccionan todas.

Permite condiciones booleanas para filtrar filas.

### <span style="color:darksalmon;">.iloc[ ]: Selección basada en índices numéricos (enteros) de filas y columnas.</span>

```python
#Sintaxis general
df.iloc[índice_filas,índice_columnas]

Uso típico de .iloc[]:

df.iloc[fila, columna]
```
Funciona por posición: el índice 0 es la primera fila/columna.

No admite etiquetas o condiciones lógicas directamente.

### Cuadro explicativo

| Método    | Basado en       | Sintaxis             | Permite condiciones | Ejemplo                   |
| --------- | --------------- | -------------------- | ------------------- | ------------------------- |
| `.loc[]`  | Etiquetas       | `df.loc["a", "col"]` | ✅ Sí                | `df.loc[df["edad"] > 30]` |
| `.iloc[]` | Índices enteros | `df.iloc[0, 1]`      | ❌ No                | `df.iloc[0:3, :]`         |

### <span style="color:darksalmon;"> Veamos un ejemplo con un  DataFrame:</span>

In [6]:
import pandas as pd
# Cargar archivo CSV en un DataFrame
df = pd.read_csv('Online Sales Data.csv')

In [7]:
df.sample(5)

,Transaction ID,Date,Product Category,Product Name,Units Sold,Unit Price,Total Revenue,Region,Payment Method
146,10147,2024-05-26,Clothing,Levi's Sherpa Trucker Jacket,2,98.00,196.00,Asia,Debit Card
109,10110,2024-04-19,Home Appliances,Cuisinart Griddler Deluxe,1,159.99,159.99,Europe,PayPal
61,10062,2024-03-02,Home Appliances,Philips Airfryer XXL,2,199.99,399.98,Europe,PayPal
104,10105,2024-04-14,Clothing,H&M Slim Fit Jeans,3,39.99,119.97,Asia,Debit Card
235,10236,2024-08-23,Home Appliances,Nespresso Vertuo Next Coffee and Espresso Maker,1,159.99,159.99,Europe,PayPal

- Selecciona todas las ventas y muestra las columnas `Date`, `Product Category` y `Unit Price` usando `loc[ ]`

In [8]:
df.loc[:,['Date', 'Product Category', 'Units Sold']]

           Date Product Category  Units Sold
0    2024-01-01      Electronics           2
1    2024-01-02  Home Appliances           1
2    2024-01-03         Clothing           3
3    2024-01-04            Books           4
4    2024-01-05  Beauty Products           1
..          ...              ...         ...
235  2024-08-23  Home Appliances           1
236  2024-08-24         Clothing           3
237  2024-08-25            Books           3
238  2024-08-26  Beauty Products           1
239  2024-08-27           Sports           2

[240 rows x 3 columns]

In [9]:
df.loc[20:30:3,['Date', 'Product Category', 'Units Sold']]

          Date Product Category  Units Sold
20  2024-01-21         Clothing           3
23  2024-01-24           Sports           3
26  2024-01-27         Clothing           2
29  2024-01-30           Sports           2

- Utiliza `iloc [ ]` para seleccionar las primeras 10 filas del DataFrame y muestra las columnas `Product Category` , `Product Name` y `Unit Price`

In [20]:
df.iloc[:10,[2,3,5]]

  Product Category                 Product Name  Unit Price
0      Electronics                iPhone 14 Pro      999.99
1  Home Appliances             Dyson V11 Vacuum      499.99
2         Clothing             Levi's 501 Jeans       69.99
3            Books            The Da Vinci Code       15.99
4  Beauty Products      Neutrogena Skincare Set       89.99
5           Sports  Wilson Evolution Basketball       29.99
6      Electronics          MacBook Pro 16-inch     2499.99
7  Home Appliances         Blueair Classic 480i      599.99
8         Clothing             Nike Air Force 1       89.99
9            Books        Dune by Frank Herbert       25.99

### En Pandas existen varios métodos para poder filtrar los datos de un DataFrame. Los más comunes son:

- **Operadores de comparación**: Son básicamente los mismos que vimos en el módulo de Python. Es una forma de filtrado muy útil para seleccionar filas basadas en condiciones. Los pasos a seguir serían:

    - **Creamos la condición:** Para ello usaremos los operadores de comparación de Python (>, <, >=, <=, ==, !=)

    - **Aplicar la condición de filtrado:** Una vez creada la condición es momento de aplicarla con [ ] al DataFrame. Esto nos devolverá las filas que cumplen la condición.

    - **Combinar condiciones:** Es posible combinar varias condiciones utilizando los operadores **&** (*and*) y **|** (*or*).

    ```python
    unit_price = df['Unit Price'] > 1000
    unit_sold = df['Units Sold'] > 5
    
    df[unit_price & unit_sold].loc[:,['Product Name', 'Product Category', 'Unit Price', 'Units Sold']]
    ```

### Veámoslo con un ejemplo:

In [10]:
unit_price = df['Unit Price'] > 100
unit_sold = df['Units Sold'] > 2

In [11]:
df[unit_price & unit_sold].loc[:,['Product Name', 'Product Category', 'Unit Price', 'Units Sold']]

                         Product Name Product Category  Unit Price  Units Sold
11   Babolat Pure Drive Tennis Racket           Sports      199.99           3
17               Manduka PRO Yoga Mat           Sports      119.99           4
36               Apple Watch Series 8      Electronics      399.99           3
42                 GoPro HERO10 Black      Electronics      399.99           3
50         Ray-Ban Aviator Sunglasses         Clothing      154.99           3
60                    Nintendo Switch      Electronics      299.99           3
67                   Eufy RoboVac 11S  Home Appliances      219.99           3
71                      Nike Metcon 6           Sports      129.99           3
96    Bose SoundLink Revolve+ Speaker      Electronics      299.99           3
113                    Fitbit Versa 3           Sports      229.95           3

### Veamos algunas otras posibilidades de Filtrado:

1. Filtrar todas las transacciones hechas con PayPal:

In [12]:
paypal_df = df[df["Payment Method"] == "Credit Card"]
paypal_df

,Transaction ID,Date,Product Category,Product Name,Units Sold,Unit Price,Total Revenue,Region,Payment Method
0,10001,2024-01-01,Electronics,iPhone 14 Pro,2,999.99,1999.98,North America,Credit Card
3,10004,2024-01-04,Books,The Da Vinci Code,4,15.99,63.96,North America,Credit Card
5,10006,2024-01-06,Sports,Wilson Evolution Basketball,5,29.99,149.95,Asia,Credit Card
6,10007,2024-01-07,Electronics,MacBook Pro 16-inch,1,2499.99,2499.99,North America,Credit Card
9,10010,2024-01-10,Books,Dune by Frank Herbert,2,25.99,51.98,North America,Credit Card
...,...,...,...,...,...,...,...,...,...
231,10232,2024-08-19,Books,Dune by Frank Herbert,2,9.99,19.98,North America,Credit Card
233,10234,2024-08-21,Sports,Hydro Flask Standard Mouth Water Bottle,3,32.95,98.85,Asia,Credit Card
234,10235,2024-08-22,Electronics,Bose QuietComfort 35 II Wireless Headphones,1,299.00,299.00,North America,Credit Card
237,10238,2024-08-25,Books,The Handmaid's Tale by Margaret Atwood,3,10.99,32.97,North America,Credit Card
239,10240,2024-08-27,Sports,Yeti Rambler 20 oz Tumbler,2,29.99,59.98,Asia,Credit Card

2. Filtrar productos vendidos en la región Asia

In [15]:
asia_df = df[df["Region"] == "Asia"]
asia_df

,Transaction ID,Date,Product Category,Product Name,Units Sold,Unit Price,Total Revenue,Region,Payment Method
2,10003,2024-01-03,Clothing,Levi's 501 Jeans,3,69.99,209.97,Asia,Debit Card
5,10006,2024-01-06,Sports,Wilson Evolution Basketball,5,29.99,149.95,Asia,Credit Card
8,10009,2024-01-09,Clothing,Nike Air Force 1,6,89.99,539.94,Asia,Debit Card
11,10012,2024-01-12,Sports,Babolat Pure Drive Tennis Racket,3,199.99,599.97,Asia,Credit Card
14,10015,2024-01-15,Clothing,North Face Down Jacket,2,249.99,499.98,Asia,Debit Card
...,...,...,...,...,...,...,...,...,...
227,10228,2024-08-15,Sports,Fitbit Luxe,2,149.95,299.90,Asia,Credit Card
230,10231,2024-08-18,Clothing,Adidas Originals Trefoil Hoodie,4,64.99,259.96,Asia,Debit Card
233,10234,2024-08-21,Sports,Hydro Flask Standard Mouth Water Bottle,3,32.95,98.85,Asia,Credit Card
236,10237,2024-08-24,Clothing,Nike Air Force 1 Sneakers,3,90.00,270.00,Asia,Debit Card
239,10240,2024-08-27,Sports,Yeti Rambler 20 oz Tumbler,2,29.99,59.98,Asia,Credit Card

3. Filtrar productos vendidos en la región Asia , pero solo mostrar las columnas Product Category y Product Name

In [16]:
resultado = df.loc[df["Region"] == "Asia", ["Product Category", "Product Name"]]
resultado

    Product Category                             Product Name
2           Clothing                         Levi's 501 Jeans
5             Sports              Wilson Evolution Basketball
8           Clothing                         Nike Air Force 1
11            Sports         Babolat Pure Drive Tennis Racket
14          Clothing                   North Face Down Jacket
..               ...                                      ...
227           Sports                              Fitbit Luxe
230         Clothing          Adidas Originals Trefoil Hoodie
233           Sports  Hydro Flask Standard Mouth Water Bottle
236         Clothing                Nike Air Force 1 Sneakers
239           Sports               Yeti Rambler 20 oz Tumbler

[80 rows x 2 columns]

---
###  Filtrado con .isin() 
---

El método .isin( ) se utiliza para filtrar filas que contienen uno o varios valores específicos dentro de una columna. 

Es muy útil cuando queremos comprobar si un valor pertenece a una lista de opciones.

### Pasos:

- Crear una lista de valores de interés

- Aplicar .isin(lista) a una columna específica

- Combinar con un filtro booleano y seleccionar columnas si se desea

Ejemplo 1: Transacciones en la región "Asia" o "Europe"

In [17]:
regiones = ["Asia", "Europe"]
filtro = df[df["Region"].isin(regiones)]
filtro

,Transaction ID,Date,Product Category,Product Name,Units Sold,Unit Price,Total Revenue,Region,Payment Method
1,10002,2024-01-02,Home Appliances,Dyson V11 Vacuum,1,499.99,499.99,Europe,PayPal
2,10003,2024-01-03,Clothing,Levi's 501 Jeans,3,69.99,209.97,Asia,Debit Card
4,10005,2024-01-05,Beauty Products,Neutrogena Skincare Set,1,89.99,89.99,Europe,PayPal
5,10006,2024-01-06,Sports,Wilson Evolution Basketball,5,29.99,149.95,Asia,Credit Card
7,10008,2024-01-08,Home Appliances,Blueair Classic 480i,2,599.99,1199.98,Europe,PayPal
...,...,...,...,...,...,...,...,...,...
233,10234,2024-08-21,Sports,Hydro Flask Standard Mouth Water Bottle,3,32.95,98.85,Asia,Credit Card
235,10236,2024-08-23,Home Appliances,Nespresso Vertuo Next Coffee and Espresso Maker,1,159.99,159.99,Europe,PayPal
236,10237,2024-08-24,Clothing,Nike Air Force 1 Sneakers,3,90.00,270.00,Asia,Debit Card
238,10239,2024-08-26,Beauty Products,Sunday Riley Luna Sleeping Night Oil,1,55.00,55.00,Europe,PayPal
239,10240,2024-08-27,Sports,Yeti Rambler 20 oz Tumbler,2,29.99,59.98,Asia,Credit Card

In [18]:
filtro[["Transaction ID", "Region", "Product Name"]]

     Transaction ID  Region                                     Product Name
1             10002  Europe                                 Dyson V11 Vacuum
2             10003    Asia                                 Levi's 501 Jeans
4             10005  Europe                          Neutrogena Skincare Set
5             10006    Asia                      Wilson Evolution Basketball
7             10008  Europe                             Blueair Classic 480i
..              ...     ...                                              ...
233           10234    Asia          Hydro Flask Standard Mouth Water Bottle
235           10236  Europe  Nespresso Vertuo Next Coffee and Espresso Maker
236           10237    Asia                        Nike Air Force 1 Sneakers
238           10239  Europe             Sunday Riley Luna Sleeping Night Oil
239           10240    Asia                       Yeti Rambler 20 oz Tumbler

[160 rows x 3 columns]

Ejemplo 2: Productos específicos – "Gap High Rise Skinny Jeans" o "Hanes ComfortSoft T-Shirt"

In [21]:
productos = ["Gap High Rise Skinny Jeans", "Hanes ComfortSoft T-Shirt"]
filtro = df[df["Product Name"].isin(productos)]
filtro[["Product Name", "Units Sold", "Region"]]

                   Product Name  Units Sold Region
62    Hanes ComfortSoft T-Shirt          10   Asia
116  Gap High Rise Skinny Jeans           3   Asia

Ejemplo 3: Productos vendidos en Asia que estén en una lista específica

In [22]:
productos = ["Gap High Rise Skinny Jeans", "Gap 1969 Original Fit Jeans"]
filtro = df[df["Region"].isin(["Asia"]) & df["Product Name"].isin(productos)]
filtro[["Product Category", "Product Name", "Units Sold"]]

    Product Category                 Product Name  Units Sold
116         Clothing   Gap High Rise Skinny Jeans           3
200         Clothing  Gap 1969 Original Fit Jeans           3

Ejemplo 4: Producto "Gap 1969 Original Fit Jeans" vendido en "Asia"

In [ ]:
producto = ["Gap 1969 Original Fit Jeans"]
region = ["Asia"]

filtro = df[df["Product Name"].isin(producto) & df["Region"].isin(region)]
filtro[["Transaction ID", "Product Name", "Units Sold", "Total Revenue"]]

---
###  Filtrado con .between( )
---

El método .between() se usa para filtrar filas en un DataFrame que tengan valores dentro de un rango numérico o de fechas.

La estructura general de este método es:

```python

df[columna].between(inicio, fin, inclusive = both)

'''Donde:

- df: Nombre del DataFrame que vamos a utilizar.
- columna: Columna específica donde vamos a filtrar.
- inicio y fin: Indica el intervalo de valores que queremos filtrar.
- inclusive (opcional): Delimita si los valores del rango están incluidos o no.
    - left: Incluye sólo el inicio.
    - right: Incluye sólo el final.
    - both: Incluye ambos.
    - neither: No incluye ninguno.'''
```

| Parámetro   | Descripción                                                                             |
| ----------- | --------------------------------------------------------------------------------------- |
| `columna`   | Columna sobre la que se aplica el filtro.                                               |
| `inicio`    | Valor mínimo del rango.                                                                 |
| `fin`       | Valor máximo del rango.                                                                 |
| `inclusive` | Define si se incluyen los límites. Valores: `'both'`, `'left'`, `'right'`, `'neither'`. |

Ejemplo 1: Unit Price entre 10 y 50 (inclusive ambos)

In [23]:
df[df["Unit Price"].between(10, 50, inclusive="both")][["Transaction ID", "Product Name", "Unit Price", "Units Sold"]]

,Transaction ID,Product Name,Unit Price,Units Sold
3,10004,The Da Vinci Code,15.99,4
5,10006,Wilson Evolution Basketball,29.99,5
9,10010,Dune by Frank Herbert,25.99,2
15,10016,"Salt, Fat, Acid, Heat by Samin Nosrat",35.99,3
21,10022,Gone Girl by Gillian Flynn,22.99,2
...,...,...,...,...
225,10226,The Silent Patient by Alex Michaelides,26.99,3
232,10233,Fresh Sugar Lip Treatment,24.00,1
233,10234,Hydro Flask Standard Mouth Water Bottle,32.95,3
237,10238,The Handmaid's Tale by Margaret Atwood,10.99,3
239,10240,Yeti Rambler 20 oz Tumbler,29.99,2

Ejemplo 2: Total Revenue entre 100 y 180 (solo extremos)

In [25]:
df[df["Total Revenue"].between(100, 180, inclusive="right")][["Transaction ID", "Product Name", "Total Revenue"]]

,Transaction ID,Product Name,Total Revenue
5,10006,Wilson Evolution Basketball,149.95
10,10011,Chanel No. 5 Perfume,129.99
15,10016,"Salt, Fat, Acid, Heat by Samin Nosrat",107.97
20,10021,Zara Summer Dress,179.97
25,10026,Panasonic NN-SN966S Microwave,179.99
32,10033,Under Armour HeatGear T-Shirt,149.95
40,10041,Estee Lauder Advanced Night Repair,105.00
45,10046,Becoming by Michelle Obama,130.00
56,10057,Calvin Klein Boxer Briefs,149.95
64,10065,Lancome La Vie Est Belle,102.00
80,10081,Levi's Trucker Jacket,179.98
83,10084,Spalding NBA Street Basketball,149.94
88,10089,Sunday Riley Good Genes,105.00
91,10092,Instant Pot Duo Crisp,179.99
98,10099,Gap Essential Crewneck T-Shirt,119.94
104,10105,H&M Slim Fit Jeans,119.97
109,10110,Cuisinart Griddler Deluxe,159.99
116,10117,Gap High Rise Skinny Jeans,149.97
131,10132,Hydro Flask Wide Mouth Water Bottle,159.80
133,10134,Keurig K-Mini Coffee Maker,159.98
134,10135,Gap Crewneck Sweatshirt,139.96
139,10140,Instant Pot Ultra,139.99
140,10141,Adidas Essential Track Pants,134.97
152,10153,Nike Sportswear Club Fleece Hoodie,164.97
164,10165,Adidas 3-Stripes Shorts,149.95
167,10168,Yeti Rambler Bottle,149.97
170,10171,Nike Tempo Running Shorts,104.97
174,10175,Amazon Fire TV Stick 4K,149.97
179,10180,Oakley Holbrook Sunglasses,146.00
182,10183,Levi's 511 Slim Fit Jeans,179.97
188,10189,Nike Dri-FIT Training Shorts,139.96
191,10192,TRX All-in-One Suspension Training System,169.95
196,10197,Tom Ford Black Orchid Perfume,125.00
200,10201,Gap 1969 Original Fit Jeans,179.97
209,10210,Bose SoundLink Color Bluetooth Speaker II,129.00
218,10219,Champion Reverse Weave Hoodie,149.97
228,10229,Google Nest Wifi Router,169.00
235,10236,Nespresso Vertuo Next Coffee and Espresso Maker,159.99

Ejemplo 3: Units Sold entre 2 y 5 (excluyendo ambos límites)

In [27]:
df[df["Units Sold"].between(2, 5 , inclusive= 'neither')][["Product Name", "Units Sold"]]

                                Product Name  Units Sold
2                           Levi's 501 Jeans           3
3                          The Da Vinci Code           4
11          Babolat Pure Drive Tennis Racket           3
15     Salt, Fat, Acid, Heat by Samin Nosrat           3
17                      Manduka PRO Yoga Mat           4
..                                       ...         ...
225   The Silent Patient by Alex Michaelides           3
230          Adidas Originals Trefoil Hoodie           4
233  Hydro Flask Standard Mouth Water Bottle           3
236                Nike Air Force 1 Sneakers           3
237   The Handmaid's Tale by Margaret Atwood           3

[67 rows x 2 columns]

 Ejemplo 4: Filtrar por fecha entre "2024-03-01" y "2024-06-30"

In [28]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 240 entries, 0 to 239
Data columns (total 9 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Transaction ID    240 non-null    int64
 1   Date              240 non-null    object
 2   Product Category  240 non-null    object
 3   Product Name      240 non-null    object
 4   Units Sold        240 non-null    int64
 5   Unit Price        240 non-null    float64
 6   Total Revenue     240 non-null    float64
 7   Region            240 non-null    object
 8   Payment Method    240 non-null    object
dtypes: float64(2), int64(2), object(5)
memory usage: 17.0+ KB

In [31]:
df["Date"] = pd.to_datetime(df["Date"])#para transformar a Fecha

df[df["Product Name"].isin(['Philips Airfryer XXL']) & df["Date"].between("2024-03-01", "2024-06-30" , inclusive='neither')][["Transaction ID", "Date", "Product Name"]]

    Transaction ID       Date          Product Name
61           10062 2024-03-02  Philips Airfryer XXL

---
###  Filtrado con .str.contains( )
---

El método `.str.contains()` permite verificar si una cadena de texto contiene un patrón específico (palabra, fragmento, regex). 

Muy útil cuando buscamos por nombre de producto, descripción o categoría.

```Python 
#sintaxis
df["columna"].str.contains(pat, case=True, na=False, regex=True)

```

 Parámetros clave:

| Parámetro | Significado                                                      |
| --------- | ---------------------------------------------------------------- |
| `pat`     | Texto o patrón a buscar. Puede ser string o regex.               |
| `case`    | `True` → sensible a mayúsculas/minúsculas; `False` → insensible. |
| `na`      | Cómo tratar los valores nulos (`True`, `False`, o `np.nan`).     |
| `regex`   | Si se trata como expresión regular (por defecto `True`).         |

| Ejemplo                                                  | Significado                                        |
| -------------------------------------------------------- | -------------------------------------------------- |
| `df["col"].str.contains("Mug")`                          | Contiene exactamente "Mug" (sensible a mayúsculas) |
| `df["col"].str.contains("mug", case=False)`              | Contiene "mug", sin importar mayúsculas            |
| `df["col"].str.contains("^Gap", case=False, regex=True)` | Comienza con "Gap" (regex)                         |

 Ejemplo 1: Productos cuyo nombre contiene "Jeans"

In [32]:
df[df["Product Name"].str.contains("Jeans", case=True, na=False)]

,Transaction ID,Date,Product Category,Product Name,Units Sold,Unit Price,Total Revenue,Region,Payment Method
2,10003,2024-01-03,Clothing,Levi's 501 Jeans,3,69.99,209.97,Asia,Debit Card
104,10105,2024-04-14,Clothing,H&M Slim Fit Jeans,3,39.99,119.97,Asia,Debit Card
116,10117,2024-04-26,Clothing,Gap High Rise Skinny Jeans,3,49.99,149.97,Asia,Debit Card
182,10183,2024-07-01,Clothing,Levi's 511 Slim Fit Jeans,3,59.99,179.97,Asia,Debit Card
200,10201,2024-07-19,Clothing,Gap 1969 Original Fit Jeans,3,59.99,179.97,Asia,Debit Card
224,10225,2024-08-12,Clothing,Old Navy Mid-Rise Rockstar Super Skinny Jeans,2,44.99,89.98,Asia,Debit Card

Ejemplo 2: Productos que contienen la palabra "gap" (sin importar mayúsculas)

In [35]:
df[df["Product Name"].str.contains("GA", case=False, na=False)][["Product Name", "Product Category"]]

                                 Product Name Product Category
12                      Samsung Galaxy Tab S8      Electronics
17                       Manduka PRO Yoga Mat           Sports
18                      Garmin Forerunner 945      Electronics
29                   Nike Air Zoom Pegasus 37           Sports
65                            Garmin Edge 530           Sports
69    The Great Gatsby by F. Scott Fitzgerald            Books
95                        Garmin Fenix 6X Pro           Sports
98             Gap Essential Crewneck T-Shirt         Clothing
116                Gap High Rise Skinny Jeans         Clothing
134                   Gap Crewneck Sweatshirt         Clothing
138         Samsung Odyssey G9 Gaming Monitor      Electronics
155                     Garmin Forerunner 245           Sports
165       The Hunger Games by Suzanne Collins            Books
168         Samsung Odyssey G7 Gaming Monitor      Electronics
192  Logitech G Pro X Wireless Gaming Headset      Electronics
200               Gap 1969 Original Fit Jeans         Clothing
204                    Samsung Galaxy Watch 4      Electronics
219         The Nightingale by Kristin Hannah            Books
221                     Garmin Forerunner 945           Sports
232                 Fresh Sugar Lip Treatment  Beauty Products
237    The Handmaid's Tale by Margaret Atwood            Books

Ejemplo 3: Productos cuyo nombre empieza con “Hanes”

In [37]:
df[df["Product Name"].str.contains("^gA", case=False, na=False, regex=True)][["Product Name", "Region" ,"Unit Price"]]

                       Product Name         Region  Unit Price
18            Garmin Forerunner 945  North America      499.99
65                  Garmin Edge 530           Asia      299.99
95              Garmin Fenix 6X Pro           Asia      999.99
98   Gap Essential Crewneck T-Shirt           Asia       19.99
116      Gap High Rise Skinny Jeans           Asia       49.99
134         Gap Crewneck Sweatshirt           Asia       34.99
155           Garmin Forerunner 245           Asia      299.99
200     Gap 1969 Original Fit Jeans           Asia       59.99
221           Garmin Forerunner 945           Asia      599.99

Ejemplo 4: Filtrar productos que contengan la palabra “water” (insensible a mayúsculas)

In [38]:
df[df["Product Name"].str.contains("water", case=False, na=False)][["Product Name", "Total Revenue"]]

                                    Product Name  Total Revenue
94                        Tatcha The Water Cream          68.00
112  Biore UV Aqua Rich Watery Essence Sunscreen          15.00
131          Hydro Flask Wide Mouth Water Bottle         159.80
148                  Laneige Water Sleeping Mask          25.00
166             Neutrogena Hydro Boost Water Gel          16.99
233      Hydro Flask Standard Mouth Water Bottle          98.85

---
###  Filtrado con .filter( )
---

El método .filter() se utiliza para filtrar columnas o filas basándose en sus etiquetas (nombres). No filtra por contenido, sino por coincidencia del nombre de columnas o índices.

```python
df.filter(items = None, like = None, regex = None,axis = None)

'''
Donde:

- df: Nombre del DataFrame que vamos a utilizar.
- items (opcional): Lista con las etiquetas que queremos filtrar.
- like (opcional): Patrón de texto que debe tener la etiqueta a filtrar.
- regex (opcional): La etiqueta debe tener la expresión regular especificada.
- axis: 0 para ver las filas que cumplen la condición. 1 para ver las columnas.
'''
```
Parámetros clave:

| Parámetro | Uso                                                                           |
| --------- | ----------------------------------------------------------------------------- |
| `items`   | Lista exacta de nombres de columnas o filas que se quieren mantener.          |
| `like`    | Texto que debe estar incluido en el nombre (como `contains` pero en nombres). |
| `regex`   | Expresión regular aplicada a los nombres de las columnas o filas.             |
| `axis`    | `0` para filas (índices), `1` para columnas.                                  |



| Ejemplo                                       | Resultado                                       |
| --------------------------------------------- | ----------------------------------------------- |
| `df.filter(like="Price", axis=1)`             | Selecciona columnas que contengan “Price”       |
| `df.filter(items=["Product Name", "Region"])` | Selecciona solo esas columnas exactas           |
| `df.filter(regex="^P.*e$", axis=1)`           | Columnas que empiezan con “P” y terminan en “e” |

Ejemplo 1: Seleccionar todas las columnas que contienen la palabra "Product"

In [48]:
df.filter(like="Product", axis=1)

    Product Category                                     Product Name
0        Electronics                                    iPhone 14 Pro
1    Home Appliances                                 Dyson V11 Vacuum
2           Clothing                                 Levi's 501 Jeans
3              Books                                The Da Vinci Code
4    Beauty Products                          Neutrogena Skincare Set
..               ...                                              ...
235  Home Appliances  Nespresso Vertuo Next Coffee and Espresso Maker
236         Clothing                        Nike Air Force 1 Sneakers
237            Books           The Handmaid's Tale by Margaret Atwood
238  Beauty Products             Sunday Riley Luna Sleeping Night Oil
239           Sports                       Yeti Rambler 20 oz Tumbler

[240 rows x 2 columns]

Ejemplo 2: Seleccionar las columnas "Product Name" y "Region" usando items

In [47]:
df.filter(items=["Product Name", "Region"], axis=1)

                                        Product Name         Region
0                                      iPhone 14 Pro  North America
1                                   Dyson V11 Vacuum         Europe
2                                   Levi's 501 Jeans           Asia
3                                  The Da Vinci Code  North America
4                            Neutrogena Skincare Set         Europe
..                                               ...            ...
235  Nespresso Vertuo Next Coffee and Espresso Maker         Europe
236                        Nike Air Force 1 Sneakers           Asia
237           The Handmaid's Tale by Margaret Atwood  North America
238             Sunday Riley Luna Sleeping Night Oil         Europe
239                       Yeti Rambler 20 oz Tumbler           Asia

[240 rows x 2 columns]

Ejemplo 3: Seleccionar columnas que empiezan con la letra "P" y terminan en "e"

In [49]:
df.filter(regex="^P.*e$", axis=1)

                                        Product Name
0                                      iPhone 14 Pro
1                                   Dyson V11 Vacuum
2                                   Levi's 501 Jeans
3                                  The Da Vinci Code
4                            Neutrogena Skincare Set
..                                               ...
235  Nespresso Vertuo Next Coffee and Espresso Maker
236                        Nike Air Force 1 Sneakers
237           The Handmaid's Tale by Margaret Atwood
238             Sunday Riley Luna Sleeping Night Oil
239                       Yeti Rambler 20 oz Tumbler

[240 rows x 1 columns]

Ejemplo 4: Seleccionar columnas que contengan la palabra "Revenue"

In [50]:
df.filter(like="Revenue", axis=1)

     Total Revenue
0          1999.98
1           499.99
2           209.97
3            63.96
4            89.99
..             ...
235         159.99
236         270.00
237          32.97
238          55.00
239          59.98

[240 rows x 1 columns]

Ejemplo 5: Seleccionar filas que tengan un índice específico (si el DataFrame tuviera un índice por ID)

Esto solo aplica si has hecho algo como df.set_index("Transaction ID")

In [54]:
df.set_index("Transaction ID").filter(items=[10020, 10205], axis=0)

,Date,Product Category,Product Name,Units Sold,Unit Price,Total Revenue,Region,Payment Method
10020,2024-01-20,Home Appliances,Ninja Professional Blender,1,99.99,99.99,Europe,PayPal
10205,2024-07-23,Electronics,Samsung Galaxy Watch 4,1,299.99,299.99,North America,Credit Card