### <span style="color:darksalmon;"> En Pandas, tambien podemos generar columnas </span>

Crear columnas en Pandas es una de las tareas más frecuentes. Podemos hacerlo de varias maneras, dependiendo de si queremos modificar el DataFrame original o crear una copia. 

Estas columnas pueden generarse a partir de cálculos, condiciones, funciones o valores constantes.

Métodos principales

- Asignación directa:

        Se utiliza para crear columnas directamente con una operación, lista, constante o condición.

- Método .assign( ):

        Crea una copia del DataFrame original con nuevas columnas, sin modificar el original.

- Método .insert( ):

        Inserta una nueva columna en una posición específica del DataFrame.


Cuadro explicativo:

| Método                         | Modifica el original | Devuelve copia | Uso típico                      |
| ------------------------------ | -------------------- | -------------- | ------------------------------- |
| Asignación `df["nueva"] = ...` | ✅                    | ❌              | Rápido y directo                |
| `.assign()`                    | ❌                    | ✅              | Múltiples columnas, más control |
| `.insert()`                    | ✅                    | ❌              | Control total de la posición    |

Ejemplo 1: Asignación directa , Crear una columna Discount con valores aleatorios entre 0% y 20% (como decimales)

In [10]:
import pandas as pd
import numpy as np
# Cargar archivo CSV en un DataFrame
df = pd.read_csv('Online_Sales_modificado.csv')
df.head(5)

,Transaction ID,Date,Product Category,Product Name,Units Sold,Unit Price,Total Revenue,Region,Payment Method,Total_Revenue_recal,Dif_Revenue,Precio con IVA,Ingreso por unidad,Precio con descuento,Unidades futuras
0,10001,2024-01-01,Electronics,iPhone 14 Pro,2,999.99,1999.98,North America,Credit Card,1999.98,0.0,1209.9879,999.99,899.991,4
1,10002,2024-01-02,Home Appliances,Dyson V11 Vacuum,1,499.99,499.99,Europe,PayPal,499.99,0.0,604.9879,499.99,449.991,3
2,10003,2024-01-03,Clothing,Levi's 501 Jeans,3,69.99,209.97,Asia,Debit Card,209.97,0.0,84.6879,69.99,62.991,5
3,10004,2024-01-04,Books,The Da Vinci Code,4,15.99,63.96,North America,Credit Card,63.96,0.0,19.3479,15.99,14.391,6
4,10005,2024-01-05,Beauty Products,Neutrogena Skincare Set,1,89.99,89.99,Europe,PayPal,89.99,0.0,108.8879,89.99,80.991,3

In [11]:
len(df)

240

In [12]:
df["Discount"] = np.random.randint(0, 21, size=len(df)) / 100
df.sample(7)

,Transaction ID,Date,Product Category,Product Name,Units Sold,Unit Price,Total Revenue,Region,Payment Method,Total_Revenue_recal,Dif_Revenue,Precio con IVA,Ingreso por unidad,Precio con descuento,Unidades futuras,Discount
131,10132,2024-05-11,Sports,Hydro Flask Wide Mouth Water Bottle,4,39.95,159.80,Asia,Credit Card,159.80,0.0,48.3395,39.95,35.955,6,0.08
79,10080,2024-03-20,Home Appliances,Dyson Pure Cool Link,1,499.99,499.99,Europe,PayPal,499.99,0.0,604.9879,499.99,449.991,3,0.20
25,10026,2024-01-26,Home Appliances,Panasonic NN-SN966S Microwave,1,179.99,179.99,Europe,PayPal,179.99,0.0,217.7879,179.99,161.991,3,0.07
30,10031,2024-01-31,Electronics,Sony WH-1000XM4 Headphones,2,349.99,699.98,North America,Credit Card,699.98,0.0,423.4879,349.99,314.991,4,0.12
67,10068,2024-03-08,Home Appliances,Eufy RoboVac 11S,3,219.99,659.97,Europe,PayPal,659.97,0.0,266.1879,219.99,197.991,5,0.15
161,10162,2024-06-10,Sports,TriggerPoint GRID Foam Roller,2,34.99,69.98,Asia,Credit Card,69.98,0.0,42.3379,34.99,31.491,4,0.19
222,10223,2024-08-10,Electronics,Amazon Echo Dot (4th Gen),4,49.99,199.96,North America,Credit Card,199.96,0.0,60.4879,49.99,44.991,6,0.07

Ejemplo 2: Calcular el descuento aplicado (descuento sobre ingreso total)

In [13]:
df["DescuentoAplicado"] = df["Total Revenue"] * df["Discount"]
df.head()

,Transaction ID,Date,Product Category,Product Name,Units Sold,Unit Price,Total Revenue,Region,Payment Method,Total_Revenue_recal,Dif_Revenue,Precio con IVA,Ingreso por unidad,Precio con descuento,Unidades futuras,Discount,DescuentoAplicado
0,10001,2024-01-01,Electronics,iPhone 14 Pro,2,999.99,1999.98,North America,Credit Card,1999.98,0.0,1209.9879,999.99,899.991,4,0.13,259.9974
1,10002,2024-01-02,Home Appliances,Dyson V11 Vacuum,1,499.99,499.99,Europe,PayPal,499.99,0.0,604.9879,499.99,449.991,3,0.11,54.9989
2,10003,2024-01-03,Clothing,Levi's 501 Jeans,3,69.99,209.97,Asia,Debit Card,209.97,0.0,84.6879,69.99,62.991,5,0.18,37.7946
3,10004,2024-01-04,Books,The Da Vinci Code,4,15.99,63.96,North America,Credit Card,63.96,0.0,19.3479,15.99,14.391,6,0.01,0.6396
4,10005,2024-01-05,Beauty Products,Neutrogena Skincare Set,1,89.99,89.99,Europe,PayPal,89.99,0.0,108.8879,89.99,80.991,3,0.06,5.3994

Ejemplo 3: Crear la misma columna con .assign() (sin tocar el original)

In [14]:
df_nuevo = df.assign(DescuentoAplicado_assign = df["Units Sold"] * df["Unit Price"] * df["Discount"])
df_nuevo.head()

,Transaction ID,Date,Product Category,Product Name,Units Sold,Unit Price,Total Revenue,Region,Payment Method,Total_Revenue_recal,Dif_Revenue,Precio con IVA,Ingreso por unidad,Precio con descuento,Unidades futuras,Discount,DescuentoAplicado,DescuentoAplicado_assign
0,10001,2024-01-01,Electronics,iPhone 14 Pro,2,999.99,1999.98,North America,Credit Card,1999.98,0.0,1209.9879,999.99,899.991,4,0.13,259.9974,259.9974
1,10002,2024-01-02,Home Appliances,Dyson V11 Vacuum,1,499.99,499.99,Europe,PayPal,499.99,0.0,604.9879,499.99,449.991,3,0.11,54.9989,54.9989
2,10003,2024-01-03,Clothing,Levi's 501 Jeans,3,69.99,209.97,Asia,Debit Card,209.97,0.0,84.6879,69.99,62.991,5,0.18,37.7946,37.7946
3,10004,2024-01-04,Books,The Da Vinci Code,4,15.99,63.96,North America,Credit Card,63.96,0.0,19.3479,15.99,14.391,6,0.01,0.6396,0.6396
4,10005,2024-01-05,Beauty Products,Neutrogena Skincare Set,1,89.99,89.99,Europe,PayPal,89.99,0.0,108.8879,89.99,80.991,3,0.06,5.3994,5.3994

Ejemplo 4: Insertar la nueva columna al inicio con .insert()

In [15]:
descuento = df["Units Sold"] * df["Unit Price"] * df["Discount"]
df.insert(5, "DescuentoAplicado_insert", descuento)

In [17]:
df

,Transaction ID,Date,Product Category,Product Name,Units Sold,DescuentoAplicado_insert,Unit Price,Total Revenue,Region,Payment Method,Total_Revenue_recal,Dif_Revenue,Precio con IVA,Ingreso por unidad,Precio con descuento,Unidades futuras,Discount,DescuentoAplicado
0,10001,2024-01-01,Electronics,iPhone 14 Pro,2,259.9974,999.99,1999.98,North America,Credit Card,1999.98,0.0,1209.9879,999.99,899.991,4,0.13,259.9974
1,10002,2024-01-02,Home Appliances,Dyson V11 Vacuum,1,54.9989,499.99,499.99,Europe,PayPal,499.99,0.0,604.9879,499.99,449.991,3,0.11,54.9989
2,10003,2024-01-03,Clothing,Levi's 501 Jeans,3,37.7946,69.99,209.97,Asia,Debit Card,209.97,0.0,84.6879,69.99,62.991,5,0.18,37.7946
3,10004,2024-01-04,Books,The Da Vinci Code,4,0.6396,15.99,63.96,North America,Credit Card,63.96,0.0,19.3479,15.99,14.391,6,0.01,0.6396
4,10005,2024-01-05,Beauty Products,Neutrogena Skincare Set,1,5.3994,89.99,89.99,Europe,PayPal,89.99,0.0,108.8879,89.99,80.991,3,0.06,5.3994
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
235,10236,2024-08-23,Home Appliances,Nespresso Vertuo Next Coffee and Espresso Maker,1,17.5989,159.99,159.99,Europe,PayPal,159.99,0.0,193.5879,159.99,143.991,3,0.11,17.5989
236,10237,2024-08-24,Clothing,Nike Air Force 1 Sneakers,3,18.9000,90.00,270.00,Asia,Debit Card,270.00,0.0,108.9000,90.00,81.000,5,0.07,18.9000
237,10238,2024-08-25,Books,The Handmaid's Tale by Margaret Atwood,3,0.0000,10.99,32.97,North America,Credit Card,32.97,0.0,13.2979,10.99,9.891,5,0.00,0.0000
238,10239,2024-08-26,Beauty Products,Sunday Riley Luna Sleeping Night Oil,1,2.7500,55.00,55.00,Europe,PayPal,55.00,0.0,66.5500,55.00,49.500,3,0.05,2.7500
239,10240,2024-08-27,Sports,Yeti Rambler 20 oz Tumbler,2,0.5998,29.99,59.98,Asia,Credit Card,59.98,0.0,36.2879,29.99,26.991,4,0.01,0.5998

In [19]:
df.columns

Index(['Transaction ID', 'Date', 'Product Category', 'Product Name',
       'Units Sold', 'DescuentoAplicado_insert', 'Unit Price', 'Total Revenue',
       'Region', 'Payment Method', 'Total_Revenue_recal', 'Dif_Revenue',
       'Precio con IVA', 'Ingreso por unidad', 'Precio con descuento',
       'Unidades futuras', 'Discount', 'DescuentoAplicado'],
      dtype='object')